# Generated by Django 4.2.4 on 2023-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maktab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('oquvchilar_soni', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='xonalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xonanomi', models.CharField(default='', max_length=221)),
                ('nechikishiligi', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
